org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
VERSION=2.0.0-alpha02
GROUP_NAME=com.qmdeve.blurview
DESCRIPTION=Android UI Component Library that provides real-time, dynamic Gaussian Blur effects. It uses native C++ code for efficient blur processing and provides a set of Blur UI Components to enhance your application design
WEBSITE=https://blurview.qmdeve.com